

import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/ModeToogle";
import "./globals.css";
import { Link } from "lucide-react";
export const metadata: Metadata = {
  title: "Project Nonton | Gua",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="p-4 flex gap-12 items-center font-bold">
              <ModeToggle />
              <Link 
                href={'/videos'} 
                className="bg-slate-200 p-2 rounded-md dark:text-green-400 text-yellow-400">
                  Nonton Project Gue
              </Link>
            </div>
            <div className="p-4">{children}</div>
          </ThemeProvider>
      </body>
    </html>
  );
}
